apiVersion: v1
kind: Namespace
metadata:
  name: bank-wise-authorization-ns
  annotations:
    desc: "Namespace for bank-wise-authorization"
    proj: "Final Project K8s bank-wise-authorization"
    owner: "Alberes"
    phone: 123-456-789