apiVersion: v1
kind: Secret
metadata:
  name: bank-wise-authorization-configmap
  namespace: bank-wise-authorization-ns
  labels:
    app: bank-wise-authorization-configmap
type: kubernetes.io/basic-auth
data:
  username: c2E=
  password: bW9uZ29kYjovL2Jhbmstd2lzZS1hZG1pbjpiYW5rLXdpc2UtcGFzc0AxOTIuMTY4LjQ5LjI6MzEwMTcvYmFuay13aXNlP2F1dGhTb3VyY2U9YWRtaW4=
  USERNAME: c2E=
  MONGODB_URI: bW9uZ29kYjovL2Jhbmstd2lzZS1hZG1pbjpiYW5rLXdpc2UtcGFzc0AxOTIuMTY4LjQ5LjI6MzEwMTcvYmFuay13aXNlP2F1dGhTb3VyY2U9YWRtaW4=

stringData:
  PASSWORD: ""
  JPA_HIBERNATE_DDL_AUTO: update
  JPA_HIBERNATE_SHOW_SQL: "true"
  JPA_PROPERTIES_HIBERNATE: "true"
  MANAGEMENT_SERVER_PORT: "8081"
  LOGGIN_FILE_NAME: bank-wise-authorization.log
  INTEREST_RATE: "1.02"
  ACCESS_TOKEN_EXPIRATION: "300"
  REFRESH_TOKEN_EXPIRATION: "600"
  METRICS_SYSTEM_PROCESSOR: "false"
