apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: bank-wise-authorization-ns
  labels:
    app: bank-wise-authorization-db
spec:
  type: NodePort
  selector:
    app: mongodb-pods
  ports:
    - name: database
      nodePort: 31017
      port: 27017
      targetPort: 27017
