apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: bank-wise-authorization-ns
  labels:
    app: bank-wise-authorization-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-pods
  template:
    metadata:
      labels:
        app: mongodb-pods
    spec:
      containers:
        - name: mongodb
          image: mongo:8.0.15
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: bank-wise-admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: bank-wise-pass