apiVersion: v1
kind: Secret
metadata:
  name: mongodb-configmap
  namespace: bank-wise-authorization-ns
  labels:
    app: bank-wise-authorization-db-configmap
type: kubernetes.io/basic-auth
data:
  username: YmFuay13aXNlLWFkbWlu
  password: YmFuay13aXNlLXBhc3M=
  MONGO_INITDB_ROOT_USERNAME: YmFuay13aXNlLWFkbWlu
  MONGO_INITDB_ROOT_PASSWORD: YmFuay13aXNlLXBhc3M=